import React from 'react';

const LAST_UPDATED = 'February 22, 2026';

export default function TermsPage() {
    return (
        <main className="min-h-screen bg-zinc-950 text-zinc-100 font-sans selection:bg-indigo-500/30 pt-24 pb-20">
            <div className="max-w-3xl mx-auto px-6">
                <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>

                <div className="prose prose-invert prose-zinc max-w-none space-y-8">
                    <p className="text-zinc-400">Last updated: {LAST_UPDATED}</p>

                    <section>
                        <h2 className="text-xl font-semibold mb-4 text-zinc-200">1. Acceptance of Terms</h2>
                        <p>
                            By accessing and using Free SVG For Me, you accept and agree to be bound by the terms and provision of this agreement.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold mb-4 text-zinc-200">2. Use License</h2>
                        <p>
                            Permission is granted to temporarily download one copy of the materials (information or software) on Free SVG For Me's website for personal, non-commercial transitory viewing only.
                        </p>
                        <p className="mt-2">
                            <strong>Generated Content:</strong> SVGs generated by our AI tools are royalty-free and can be used for both personal and commercial projects without attribution. However, you may not claim ownership of the AI model itself or the underlying technology.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold mb-4 text-zinc-200">3. Disclaimer</h2>
                        <p>
                            The materials on Free SVG For Me's website are provided on an 'as is' basis. Free SVG For Me makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.
                        </p>
                        <p className="mt-2">
                            Further, Free SVG For Me does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its website or otherwise relating to such materials or on any sites linked to this site.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold mb-4 text-zinc-200">4. Limitations</h2>
                        <p>
                            In no event shall Free SVG For Me or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Free SVG For Me's website, even if Free SVG For Me or a Free SVG For Me authorized representative has been notified orally or in writing of the possibility of such damage.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold mb-4 text-zinc-200">5. Governing Law</h2>
                        <p>
                            These terms and conditions are governed by and construed in accordance with the laws of the United States and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold mb-4 text-zinc-200">6. Contact Us</h2>
                        <p>
                            If you have any questions about these Terms, please contact us at: <a href="mailto:support@freesvgforme.com" className="text-indigo-400 hover:text-indigo-300">support@freesvgforme.com</a>
                        </p>
                    </section>
                </div>
            </div>
        </main>
    );
}
